//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bkategori
    {
        public int ID { get; set; }
        public string bkat { get; set; }
        public Nullable<int> akat_id { get; set; }
    }
}
