//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ckategori
    {
        public int ID { get; set; }
        public string ckat { get; set; }
        public Nullable<int> bkat_id { get; set; }
    }
}
